### ISSUE TITLE
Remove need for container max-width in the parent container.

### ISSUE THREAD

**Issue by xWayfinder** [vaheqelyan/svelte-grid#107]
The library doesn't work unless the `max-width`  is set on the parent container like so:
```CSS
.demo-container {
  max-width: 800px;
  width: 100%;
}
```
