### ISSUE TITLE
Disabling the initial load animation? 

### ISSUE THREAD

**Issue by benwoodward** [vaheqelyan/svelte-grid#58]
Thanks for putting this component together. I have a question about the grid loading animation.. 

When the grid is initialised, all the cards animate from `{x: 0, y: 0}` into their respective positions. Which part of the codebase is responsible for this, and is it possible to provide a different animation via a prop, or disable it altogether?

**Comment by vaheqelyan** [comment]
I already thought about it, it has performance benefits, you can disable it, but I haven't tried to implement different animations
> Which part of the codebase is responsible for this

https://github.com/vaheqelyan/svelte-grid/blob/master/src/index.svelte#L8 this part :))

**Comment by vaheqelyan** [comment]
`v3.4.0` - https://svelte-grid.now.sh/examples/fast-start

**Comment by evdama** [comment]
very awesome... vice versa... where do I put hand if I want the inital load transition to take longer? I tried setting

```css
  .transition {
    transition: all 2s;
  }
```
but that didn't change anything i.e. prolonged it?

**Comment by vaheqelyan** [comment]
you can overwrite this way: but when you drag or resize it will be slow
```css
:global(.svlt-grid-item.transition) {
  transition: transform 2s;
}
```

**Comment by evdama** [comment]
I put
```css

<style>
  :global(.svlt-grid-item.transition) {
    transition: all 4s;
  }
</style>
```
inside the file containing my `<Grid>` component but the default transition during of `0.2s` is still happening so I checked and then I saw the default CSS is shadowing my custom setting
![Screen Shot 2020-11-29 at 18 35 17](https://user-images.githubusercontent.com/39374084/100549234-1a124e80-3272-11eb-856f-1373aa7b60e7.png)

It's just for testing out this feature but still, not sure why this happens... I also looked at the source and there's no `!important` in this case.
