### ISSUE TITLE
Grid items should not have background color

### ISSUE THREAD

**Issue by benwoodward** [vaheqelyan/svelte-grid#59]
This is a very minor issue, however, I think it's too opinionated for the library to decide what background color grid items should be. It makes sense for grid items to be grey in the demo, but not in the code that's shipped with the library. 

To override this I have this in my code: 

```css
:global(.svlt-grid-item) {
  background: transparent !important;
}
```
